/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyKaystephRouteImport } from './routes/why-kaysteph'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MarketReportRouteImport } from './routes/market-report'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as InvestIndexRouteImport } from './routes/invest.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as InvestTokenizedRouteImport } from './routes/invest.tokenized'
import { Route as InvestGroupBuyRouteImport } from './routes/invest.group-buy'
import { Route as AffiliateAuthRouteImport } from './routes/affiliate.auth'
import { Route as AdminAuthRouteImport } from './routes/admin.auth'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortfolioIndexRouteImport } from './routes/_authenticated/portfolio.index'
import { Route as AuthenticatedPortfolioWalletRouteImport } from './routes/_authenticated/portfolio.wallet'
import { Route as AuthenticatedPortfolioTransactionsRouteImport } from './routes/_authenticated/portfolio.transactions'
import { Route as AuthenticatedPortfolioTokensRouteImport } from './routes/_authenticated/portfolio.tokens'
import { Route as AuthenticatedPortfolioSupportRouteImport } from './routes/_authenticated/portfolio.support'
import { Route as AuthenticatedPortfolioStatementsRouteImport } from './routes/_authenticated/portfolio.statements'
import { Route as AuthenticatedPortfolioReturnsRouteImport } from './routes/_authenticated/portfolio.returns'
import { Route as AuthenticatedPortfolioPropertiesRouteImport } from './routes/_authenticated/portfolio.properties'
import { Route as AuthenticatedPortfolioProfileRouteImport } from './routes/_authenticated/portfolio.profile'
import { Route as AuthenticatedPortfolioOpportunitiesRouteImport } from './routes/_authenticated/portfolio.opportunities'
import { Route as AuthenticatedPortfolioNotificationsRouteImport } from './routes/_authenticated/portfolio.notifications'
import { Route as AuthenticatedPortfolioKycRouteImport } from './routes/_authenticated/portfolio.kyc'
import { Route as AuthenticatedPortfolioExitRequestsRouteImport } from './routes/_authenticated/portfolio.exit-requests'
import { Route as AuthenticatedPortfolioDocumentsRouteImport } from './routes/_authenticated/portfolio.documents'
import { Route as AuthenticatedPortfolioCertificatesRouteImport } from './routes/_authenticated/portfolio.certificates'
import { Route as AuthenticatedAffiliatePortalRouteImport } from './routes/_authenticated/affiliate.portal'
import { Route as AuthenticatedPortfolioPoolsIndexRouteImport } from './routes/_authenticated/portfolio.pools.index'
import { Route as AuthenticatedPortfolioPoolsIdRouteImport } from './routes/_authenticated/portfolio.pools.$id'

const WhyKaystephRoute = WhyKaystephRouteImport.update({
  id: '/why-kaysteph',
  path: '/why-kaysteph',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketReportRoute = MarketReportRouteImport.update({
  id: '/market-report',
  path: '/market-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestIndexRoute = InvestIndexRouteImport.update({
  id: '/invest/',
  path: '/invest/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestTokenizedRoute = InvestTokenizedRouteImport.update({
  id: '/invest/tokenized',
  path: '/invest/tokenized',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestGroupBuyRoute = InvestGroupBuyRouteImport.update({
  id: '/invest/group-buy',
  path: '/invest/group-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateAuthRoute = AffiliateAuthRouteImport.update({
  id: '/affiliate/auth',
  path: '/affiliate/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioIndexRoute =
  AuthenticatedPortfolioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioWalletRoute =
  AuthenticatedPortfolioWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioTransactionsRoute =
  AuthenticatedPortfolioTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioTokensRoute =
  AuthenticatedPortfolioTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioSupportRoute =
  AuthenticatedPortfolioSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioStatementsRoute =
  AuthenticatedPortfolioStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioReturnsRoute =
  AuthenticatedPortfolioReturnsRouteImport.update({
    id: '/returns',
    path: '/returns',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioPropertiesRoute =
  AuthenticatedPortfolioPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioProfileRoute =
  AuthenticatedPortfolioProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioOpportunitiesRoute =
  AuthenticatedPortfolioOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioNotificationsRoute =
  AuthenticatedPortfolioNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioKycRoute =
  AuthenticatedPortfolioKycRouteImport.update({
    id: '/kyc',
    path: '/kyc',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioExitRequestsRoute =
  AuthenticatedPortfolioExitRequestsRouteImport.update({
    id: '/exit-requests',
    path: '/exit-requests',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioDocumentsRoute =
  AuthenticatedPortfolioDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioCertificatesRoute =
  AuthenticatedPortfolioCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedAffiliatePortalRoute =
  AuthenticatedAffiliatePortalRouteImport.update({
    id: '/affiliate/portal',
    path: '/affiliate/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortfolioPoolsIndexRoute =
  AuthenticatedPortfolioPoolsIndexRouteImport.update({
    id: '/pools/',
    path: '/pools/',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioPoolsIdRoute =
  AuthenticatedPortfolioPoolsIdRouteImport.update({
    id: '/pools/$id',
    path: '/pools/$id',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/market-report': typeof MarketReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/why-kaysteph': typeof WhyKaystephRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portfolio': typeof AuthenticatedPortfolioRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/affiliate/auth': typeof AffiliateAuthRoute
  '/invest/group-buy': typeof InvestGroupBuyRoute
  '/invest/tokenized': typeof InvestTokenizedRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/invest/': typeof InvestIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/affiliate/portal': typeof AuthenticatedAffiliatePortalRoute
  '/portfolio/certificates': typeof AuthenticatedPortfolioCertificatesRoute
  '/portfolio/documents': typeof AuthenticatedPortfolioDocumentsRoute
  '/portfolio/exit-requests': typeof AuthenticatedPortfolioExitRequestsRoute
  '/portfolio/kyc': typeof AuthenticatedPortfolioKycRoute
  '/portfolio/notifications': typeof AuthenticatedPortfolioNotificationsRoute
  '/portfolio/opportunities': typeof AuthenticatedPortfolioOpportunitiesRoute
  '/portfolio/profile': typeof AuthenticatedPortfolioProfileRoute
  '/portfolio/properties': typeof AuthenticatedPortfolioPropertiesRoute
  '/portfolio/returns': typeof AuthenticatedPortfolioReturnsRoute
  '/portfolio/statements': typeof AuthenticatedPortfolioStatementsRoute
  '/portfolio/support': typeof AuthenticatedPortfolioSupportRoute
  '/portfolio/tokens': typeof AuthenticatedPortfolioTokensRoute
  '/portfolio/transactions': typeof AuthenticatedPortfolioTransactionsRoute
  '/portfolio/wallet': typeof AuthenticatedPortfolioWalletRoute
  '/portfolio/': typeof AuthenticatedPortfolioIndexRoute
  '/portfolio/pools/$id': typeof AuthenticatedPortfolioPoolsIdRoute
  '/portfolio/pools/': typeof AuthenticatedPortfolioPoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/market-report': typeof MarketReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/why-kaysteph': typeof WhyKaystephRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/auth': typeof AdminAuthRoute
  '/affiliate/auth': typeof AffiliateAuthRoute
  '/invest/group-buy': typeof InvestGroupBuyRoute
  '/invest/tokenized': typeof InvestTokenizedRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/invest': typeof InvestIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/affiliate/portal': typeof AuthenticatedAffiliatePortalRoute
  '/portfolio/certificates': typeof AuthenticatedPortfolioCertificatesRoute
  '/portfolio/documents': typeof AuthenticatedPortfolioDocumentsRoute
  '/portfolio/exit-requests': typeof AuthenticatedPortfolioExitRequestsRoute
  '/portfolio/kyc': typeof AuthenticatedPortfolioKycRoute
  '/portfolio/notifications': typeof AuthenticatedPortfolioNotificationsRoute
  '/portfolio/opportunities': typeof AuthenticatedPortfolioOpportunitiesRoute
  '/portfolio/profile': typeof AuthenticatedPortfolioProfileRoute
  '/portfolio/properties': typeof AuthenticatedPortfolioPropertiesRoute
  '/portfolio/returns': typeof AuthenticatedPortfolioReturnsRoute
  '/portfolio/statements': typeof AuthenticatedPortfolioStatementsRoute
  '/portfolio/support': typeof AuthenticatedPortfolioSupportRoute
  '/portfolio/tokens': typeof AuthenticatedPortfolioTokensRoute
  '/portfolio/transactions': typeof AuthenticatedPortfolioTransactionsRoute
  '/portfolio/wallet': typeof AuthenticatedPortfolioWalletRoute
  '/portfolio': typeof AuthenticatedPortfolioIndexRoute
  '/portfolio/pools/$id': typeof AuthenticatedPortfolioPoolsIdRoute
  '/portfolio/pools': typeof AuthenticatedPortfolioPoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/market-report': typeof MarketReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/why-kaysteph': typeof WhyKaystephRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/affiliate/auth': typeof AffiliateAuthRoute
  '/invest/group-buy': typeof InvestGroupBuyRoute
  '/invest/tokenized': typeof InvestTokenizedRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/invest/': typeof InvestIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/_authenticated/affiliate/portal': typeof AuthenticatedAffiliatePortalRoute
  '/_authenticated/portfolio/certificates': typeof AuthenticatedPortfolioCertificatesRoute
  '/_authenticated/portfolio/documents': typeof AuthenticatedPortfolioDocumentsRoute
  '/_authenticated/portfolio/exit-requests': typeof AuthenticatedPortfolioExitRequestsRoute
  '/_authenticated/portfolio/kyc': typeof AuthenticatedPortfolioKycRoute
  '/_authenticated/portfolio/notifications': typeof AuthenticatedPortfolioNotificationsRoute
  '/_authenticated/portfolio/opportunities': typeof AuthenticatedPortfolioOpportunitiesRoute
  '/_authenticated/portfolio/profile': typeof AuthenticatedPortfolioProfileRoute
  '/_authenticated/portfolio/properties': typeof AuthenticatedPortfolioPropertiesRoute
  '/_authenticated/portfolio/returns': typeof AuthenticatedPortfolioReturnsRoute
  '/_authenticated/portfolio/statements': typeof AuthenticatedPortfolioStatementsRoute
  '/_authenticated/portfolio/support': typeof AuthenticatedPortfolioSupportRoute
  '/_authenticated/portfolio/tokens': typeof AuthenticatedPortfolioTokensRoute
  '/_authenticated/portfolio/transactions': typeof AuthenticatedPortfolioTransactionsRoute
  '/_authenticated/portfolio/wallet': typeof AuthenticatedPortfolioWalletRoute
  '/_authenticated/portfolio/': typeof AuthenticatedPortfolioIndexRoute
  '/_authenticated/portfolio/pools/$id': typeof AuthenticatedPortfolioPoolsIdRoute
  '/_authenticated/portfolio/pools/': typeof AuthenticatedPortfolioPoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/market-report'
    | '/reset-password'
    | '/services'
    | '/team'
    | '/why-kaysteph'
    | '/admin'
    | '/portfolio'
    | '/admin/auth'
    | '/affiliate/auth'
    | '/invest/group-buy'
    | '/invest/tokenized'
    | '/properties/$id'
    | '/invest/'
    | '/properties/'
    | '/affiliate/portal'
    | '/portfolio/certificates'
    | '/portfolio/documents'
    | '/portfolio/exit-requests'
    | '/portfolio/kyc'
    | '/portfolio/notifications'
    | '/portfolio/opportunities'
    | '/portfolio/profile'
    | '/portfolio/properties'
    | '/portfolio/returns'
    | '/portfolio/statements'
    | '/portfolio/support'
    | '/portfolio/tokens'
    | '/portfolio/transactions'
    | '/portfolio/wallet'
    | '/portfolio/'
    | '/portfolio/pools/$id'
    | '/portfolio/pools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/market-report'
    | '/reset-password'
    | '/services'
    | '/team'
    | '/why-kaysteph'
    | '/admin'
    | '/admin/auth'
    | '/affiliate/auth'
    | '/invest/group-buy'
    | '/invest/tokenized'
    | '/properties/$id'
    | '/invest'
    | '/properties'
    | '/affiliate/portal'
    | '/portfolio/certificates'
    | '/portfolio/documents'
    | '/portfolio/exit-requests'
    | '/portfolio/kyc'
    | '/portfolio/notifications'
    | '/portfolio/opportunities'
    | '/portfolio/profile'
    | '/portfolio/properties'
    | '/portfolio/returns'
    | '/portfolio/statements'
    | '/portfolio/support'
    | '/portfolio/tokens'
    | '/portfolio/transactions'
    | '/portfolio/wallet'
    | '/portfolio'
    | '/portfolio/pools/$id'
    | '/portfolio/pools'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/market-report'
    | '/reset-password'
    | '/services'
    | '/team'
    | '/why-kaysteph'
    | '/_authenticated/admin'
    | '/_authenticated/portfolio'
    | '/admin/auth'
    | '/affiliate/auth'
    | '/invest/group-buy'
    | '/invest/tokenized'
    | '/properties/$id'
    | '/invest/'
    | '/properties/'
    | '/_authenticated/affiliate/portal'
    | '/_authenticated/portfolio/certificates'
    | '/_authenticated/portfolio/documents'
    | '/_authenticated/portfolio/exit-requests'
    | '/_authenticated/portfolio/kyc'
    | '/_authenticated/portfolio/notifications'
    | '/_authenticated/portfolio/opportunities'
    | '/_authenticated/portfolio/profile'
    | '/_authenticated/portfolio/properties'
    | '/_authenticated/portfolio/returns'
    | '/_authenticated/portfolio/statements'
    | '/_authenticated/portfolio/support'
    | '/_authenticated/portfolio/tokens'
    | '/_authenticated/portfolio/transactions'
    | '/_authenticated/portfolio/wallet'
    | '/_authenticated/portfolio/'
    | '/_authenticated/portfolio/pools/$id'
    | '/_authenticated/portfolio/pools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MarketReportRoute: typeof MarketReportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  WhyKaystephRoute: typeof WhyKaystephRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AffiliateAuthRoute: typeof AffiliateAuthRoute
  InvestGroupBuyRoute: typeof InvestGroupBuyRoute
  InvestTokenizedRoute: typeof InvestTokenizedRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  InvestIndexRoute: typeof InvestIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-kaysteph': {
      id: '/why-kaysteph'
      path: '/why-kaysteph'
      fullPath: '/why-kaysteph'
      preLoaderRoute: typeof WhyKaystephRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-report': {
      id: '/market-report'
      path: '/market-report'
      fullPath: '/market-report'
      preLoaderRoute: typeof MarketReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/': {
      id: '/invest/'
      path: '/invest'
      fullPath: '/invest/'
      preLoaderRoute: typeof InvestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/tokenized': {
      id: '/invest/tokenized'
      path: '/invest/tokenized'
      fullPath: '/invest/tokenized'
      preLoaderRoute: typeof InvestTokenizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/group-buy': {
      id: '/invest/group-buy'
      path: '/invest/group-buy'
      fullPath: '/invest/group-buy'
      preLoaderRoute: typeof InvestGroupBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate/auth': {
      id: '/affiliate/auth'
      path: '/affiliate/auth'
      fullPath: '/affiliate/auth'
      preLoaderRoute: typeof AffiliateAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio/': {
      id: '/_authenticated/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof AuthenticatedPortfolioIndexRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/wallet': {
      id: '/_authenticated/portfolio/wallet'
      path: '/wallet'
      fullPath: '/portfolio/wallet'
      preLoaderRoute: typeof AuthenticatedPortfolioWalletRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/transactions': {
      id: '/_authenticated/portfolio/transactions'
      path: '/transactions'
      fullPath: '/portfolio/transactions'
      preLoaderRoute: typeof AuthenticatedPortfolioTransactionsRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/tokens': {
      id: '/_authenticated/portfolio/tokens'
      path: '/tokens'
      fullPath: '/portfolio/tokens'
      preLoaderRoute: typeof AuthenticatedPortfolioTokensRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/support': {
      id: '/_authenticated/portfolio/support'
      path: '/support'
      fullPath: '/portfolio/support'
      preLoaderRoute: typeof AuthenticatedPortfolioSupportRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/statements': {
      id: '/_authenticated/portfolio/statements'
      path: '/statements'
      fullPath: '/portfolio/statements'
      preLoaderRoute: typeof AuthenticatedPortfolioStatementsRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/returns': {
      id: '/_authenticated/portfolio/returns'
      path: '/returns'
      fullPath: '/portfolio/returns'
      preLoaderRoute: typeof AuthenticatedPortfolioReturnsRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/properties': {
      id: '/_authenticated/portfolio/properties'
      path: '/properties'
      fullPath: '/portfolio/properties'
      preLoaderRoute: typeof AuthenticatedPortfolioPropertiesRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/profile': {
      id: '/_authenticated/portfolio/profile'
      path: '/profile'
      fullPath: '/portfolio/profile'
      preLoaderRoute: typeof AuthenticatedPortfolioProfileRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/opportunities': {
      id: '/_authenticated/portfolio/opportunities'
      path: '/opportunities'
      fullPath: '/portfolio/opportunities'
      preLoaderRoute: typeof AuthenticatedPortfolioOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/notifications': {
      id: '/_authenticated/portfolio/notifications'
      path: '/notifications'
      fullPath: '/portfolio/notifications'
      preLoaderRoute: typeof AuthenticatedPortfolioNotificationsRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/kyc': {
      id: '/_authenticated/portfolio/kyc'
      path: '/kyc'
      fullPath: '/portfolio/kyc'
      preLoaderRoute: typeof AuthenticatedPortfolioKycRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/exit-requests': {
      id: '/_authenticated/portfolio/exit-requests'
      path: '/exit-requests'
      fullPath: '/portfolio/exit-requests'
      preLoaderRoute: typeof AuthenticatedPortfolioExitRequestsRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/documents': {
      id: '/_authenticated/portfolio/documents'
      path: '/documents'
      fullPath: '/portfolio/documents'
      preLoaderRoute: typeof AuthenticatedPortfolioDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/certificates': {
      id: '/_authenticated/portfolio/certificates'
      path: '/certificates'
      fullPath: '/portfolio/certificates'
      preLoaderRoute: typeof AuthenticatedPortfolioCertificatesRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/affiliate/portal': {
      id: '/_authenticated/affiliate/portal'
      path: '/affiliate/portal'
      fullPath: '/affiliate/portal'
      preLoaderRoute: typeof AuthenticatedAffiliatePortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio/pools/': {
      id: '/_authenticated/portfolio/pools/'
      path: '/pools'
      fullPath: '/portfolio/pools/'
      preLoaderRoute: typeof AuthenticatedPortfolioPoolsIndexRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/pools/$id': {
      id: '/_authenticated/portfolio/pools/$id'
      path: '/pools/$id'
      fullPath: '/portfolio/pools/$id'
      preLoaderRoute: typeof AuthenticatedPortfolioPoolsIdRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
  }
}

interface AuthenticatedPortfolioRouteChildren {
  AuthenticatedPortfolioCertificatesRoute: typeof AuthenticatedPortfolioCertificatesRoute
  AuthenticatedPortfolioDocumentsRoute: typeof AuthenticatedPortfolioDocumentsRoute
  AuthenticatedPortfolioExitRequestsRoute: typeof AuthenticatedPortfolioExitRequestsRoute
  AuthenticatedPortfolioKycRoute: typeof AuthenticatedPortfolioKycRoute
  AuthenticatedPortfolioNotificationsRoute: typeof AuthenticatedPortfolioNotificationsRoute
  AuthenticatedPortfolioOpportunitiesRoute: typeof AuthenticatedPortfolioOpportunitiesRoute
  AuthenticatedPortfolioProfileRoute: typeof AuthenticatedPortfolioProfileRoute
  AuthenticatedPortfolioPropertiesRoute: typeof AuthenticatedPortfolioPropertiesRoute
  AuthenticatedPortfolioReturnsRoute: typeof AuthenticatedPortfolioReturnsRoute
  AuthenticatedPortfolioStatementsRoute: typeof AuthenticatedPortfolioStatementsRoute
  AuthenticatedPortfolioSupportRoute: typeof AuthenticatedPortfolioSupportRoute
  AuthenticatedPortfolioTokensRoute: typeof AuthenticatedPortfolioTokensRoute
  AuthenticatedPortfolioTransactionsRoute: typeof AuthenticatedPortfolioTransactionsRoute
  AuthenticatedPortfolioWalletRoute: typeof AuthenticatedPortfolioWalletRoute
  AuthenticatedPortfolioIndexRoute: typeof AuthenticatedPortfolioIndexRoute
  AuthenticatedPortfolioPoolsIdRoute: typeof AuthenticatedPortfolioPoolsIdRoute
  AuthenticatedPortfolioPoolsIndexRoute: typeof AuthenticatedPortfolioPoolsIndexRoute
}

const AuthenticatedPortfolioRouteChildren: AuthenticatedPortfolioRouteChildren =
  {
    AuthenticatedPortfolioCertificatesRoute:
      AuthenticatedPortfolioCertificatesRoute,
    AuthenticatedPortfolioDocumentsRoute: AuthenticatedPortfolioDocumentsRoute,
    AuthenticatedPortfolioExitRequestsRoute:
      AuthenticatedPortfolioExitRequestsRoute,
    AuthenticatedPortfolioKycRoute: AuthenticatedPortfolioKycRoute,
    AuthenticatedPortfolioNotificationsRoute:
      AuthenticatedPortfolioNotificationsRoute,
    AuthenticatedPortfolioOpportunitiesRoute:
      AuthenticatedPortfolioOpportunitiesRoute,
    AuthenticatedPortfolioProfileRoute: AuthenticatedPortfolioProfileRoute,
    AuthenticatedPortfolioPropertiesRoute:
      AuthenticatedPortfolioPropertiesRoute,
    AuthenticatedPortfolioReturnsRoute: AuthenticatedPortfolioReturnsRoute,
    AuthenticatedPortfolioStatementsRoute:
      AuthenticatedPortfolioStatementsRoute,
    AuthenticatedPortfolioSupportRoute: AuthenticatedPortfolioSupportRoute,
    AuthenticatedPortfolioTokensRoute: AuthenticatedPortfolioTokensRoute,
    AuthenticatedPortfolioTransactionsRoute:
      AuthenticatedPortfolioTransactionsRoute,
    AuthenticatedPortfolioWalletRoute: AuthenticatedPortfolioWalletRoute,
    AuthenticatedPortfolioIndexRoute: AuthenticatedPortfolioIndexRoute,
    AuthenticatedPortfolioPoolsIdRoute: AuthenticatedPortfolioPoolsIdRoute,
    AuthenticatedPortfolioPoolsIndexRoute:
      AuthenticatedPortfolioPoolsIndexRoute,
  }

const AuthenticatedPortfolioRouteWithChildren =
  AuthenticatedPortfolioRoute._addFileChildren(
    AuthenticatedPortfolioRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRouteWithChildren
  AuthenticatedAffiliatePortalRoute: typeof AuthenticatedAffiliatePortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRouteWithChildren,
  AuthenticatedAffiliatePortalRoute: AuthenticatedAffiliatePortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MarketReportRoute: MarketReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  WhyKaystephRoute: WhyKaystephRoute,
  AdminAuthRoute: AdminAuthRoute,
  AffiliateAuthRoute: AffiliateAuthRoute,
  InvestGroupBuyRoute: InvestGroupBuyRoute,
  InvestTokenizedRoute: InvestTokenizedRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  InvestIndexRoute: InvestIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
